//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwoBioInformatics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwoBioInformatics.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;4;-1;-2;-2;0;-1;-1;0;-2;-1;-1;-1;-1;-2;-1;1;0;-3;-2;0;-2;-1;-1;-1
        ///R;-1;5;0;-2;-3;1;0;-2;0;-3;-2;2;-1;-3;-2;-1;-1;-3;-2;-3;-1;-2;0;-1
        ///N;-2;0;6;1;-3;0;0;0;1;-3;-3;0;-2;-3;-2;1;0;-4;-2;-3;4;-3;0;-1
        ///D;-2;-2;1;6;-3;0;2;-1;-1;-3;-4;-1;-3;-3;-1;0;-1;-4;-3;-3;4;-3;1;-1
        ///C;0;-3;-3;-3;9;-3;-4;-3;-3;-1;-1;-3;-1;-2;-3;-1;-1;-2;-2;-1;-3;-1;-3;-1
        ///Q;-1;1;0;0;-3;5;2;-2;0;-3;-2;1;0;-3;-1;0;-1;-2;-1;-2;0;-2;4;-1
        ///E;-1;0;0;2;-4;2;5;-2;0;-3;-3;1;-2;-3;-1;0;-1;-3;-2;-2;1;-3;4;-1
        ///G;0;-2;0;-1;-3;-2;-2;6;-2;-4;-4;-2;-3;-3;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blosum {
            get {
                return ResourceManager.GetString("Blosum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA;Lys;K;Lysine
        ///AAC;Asn;N;Asparagine
        ///AAG;Lys;K;Lysine
        ///AAU;Asn;N;Asparagine
        ///ACA;Thr;T;Threonine
        ///ACC;Thr;T;Threonine
        ///ACG;Thr;T;Threonine
        ///ACU;Thr;T;Threonine
        ///AGA;Arg;R;Arginine
        ///AGC;Ser;S;Serine
        ///AGG;Arg;R;Arginine
        ///AGU;Ser;S;Serine
        ///AUA;Ile;I;Isoleucine
        ///AUC;Ile;I;Isoleucine
        ///AUG;Met;M;Methionine
        ///AUU;Ile;I;Isoleucine
        ///CAA;Gln;Q;Glutamine
        ///CAC;His;H;Histidine
        ///CAG;Gln;Q;Glutamine
        ///CAU;His;H;Histidine
        ///CCA;Pro;P;Proline
        ///CCC;Pro;P;Proline
        ///CCG;Pro;P;Proline
        ///CCU;Pro;P;Proline
        ///CGA;Arg;R;Arginine
        ///CGC; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Codons {
            get {
                return ResourceManager.GetString("Codons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;2
        ///R;-2;6
        ///N;0;0;2
        ///D;0;-1;2;4
        ///C;-2;-4;-4;-5;4
        ///Q;0;1;1;2;-5;4
        ///E;0;-1;1;3;-5;2;4
        ///G;1;-3;0;1;-3;-1;0;5
        ///H;-1;2;2;1;-3;3;1;-2;6
        ///I;-1;-2;-2;-2;-2;-2;-2;-3;-2;5
        ///L;-2;-3;-3;-4;-6;-2;-3;-4;-2;2;6
        ///K;-1;3;1;0;-5;1;0;-2;0;-2;-3;5
        ///M;-1;0;-2;-3;-5;-1;-2;-3;-2;2;4;0;6
        ///F;-4;-4;-4;-6;-4;-5;-5;-5;-2;1;2;-5;0;9
        ///P;1;0;-1;-1;-3;0;-1;-1;0;-2;-3;-1;-2;-5;6
        ///S;1;0;1;0;0;-1;0;1;-1;-1;-3;0;-2;-3;1;3
        ///T;1;-1;0;0;-2;-1;0;0;-1;0;-2;0;-1;-2;0;1;3
        ///W;-6;2;-4;-7;-8;-5;-7;-7;-3;-5;-2;-3;-4;0;-6;-2;-5;17
        ///Y;-3;-4;-2;-4;0;-4;-4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pam250 {
            get {
                return ResourceManager.GetString("Pam250", resourceCulture);
            }
        }
    }
}
