//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwoBioInformatics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwoBioInformatics.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA;Lys;K;Lysine
        ///AAC;Asn;N;Asparagine
        ///AAG;Lys;K;Lysine
        ///AAT;Asn;N;Asparagine
        ///ACA;Thr;T;Threonine
        ///ACC;Thr;T;Threonine
        ///ACG;Thr;T;Threonine
        ///ACT;Thr;T;Threonine
        ///AGA;Arg;R;Arginine
        ///AGC;Ser;S;Serine
        ///AGG;Arg;R;Arginine
        ///AGT;Ser;S;Serine
        ///ATA;Ile;I;Isoleucine
        ///ATC;Ile;I;Isoleucine
        ///ATG;Met;M;Methionine
        ///ATT;Ile;I;Isoleucine
        ///CAA;Gln;Q;Glutamine
        ///CAC;His;H;Histidine
        ///CAG;Gln;Q;Glutamine
        ///CAT;His;H;Histidine
        ///CCA;Pro;P;Proline
        ///CCC;Pro;P;Proline
        ///CCG;Pro;P;Proline
        ///CCT;Pro;P;Proline
        ///CGA;Arg;R;Arginine
        ///CGC; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Codons {
            get {
                return ResourceManager.GetString("Codons", resourceCulture);
            }
        }
    }
}
